# Generated by Django 5.0.1 on 2024-02-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_search',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
