# Generated by Django 5.0.1 on 2024-02-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='displacement',
            field=models.FloatField(),
        ),
    ]
