# Generated by Django 5.0.1 on 2024-02-09 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_car_is_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='is_search',
            new_name='is_searched',
        ),
    ]
