# Generated by Django 5.0.1 on 2024-02-05 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_car_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='vehicle_class',
            new_name='car_class',
        ),
    ]
