# Generated by Django 4.2.10 on 2024-02-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_searched',
            field=models.BooleanField(default=False),
        ),
    ]
