# Generated by Django 5.0.1 on 2024-02-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_car_is_favorite_alter_car_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
